engines:
  eslint:
    enabled: true
    config:
      extensions:
        - .js
    checks:
      complexity:
        enabled: false
  duplication:
    enabled: true
    config:
      extensions:
        - .js